name: strpsearch_env_ch_before
channels:
  - bioconda
  - schrodinger
  - conda-forge
  - defaults
dependencies:
  - qt-main
  - pymol-open-source
  - python=3.12.2
  - pandas
  - numpy
  - requests
  - typer
  - rich
  - matplotlib
  - seaborn
  - scipy
  - pip
  - foldseek
  - tmalign
  - usalign
  - gemmi
  - typing_extensions
  - biopython
  - pip:
      - protein-domain-segmentation
